/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anna Reyes
 */
public class Birthdate extends javax.swing.JFrame {

    /**
     * Creates new form Birthdate
     */
    public Birthdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bgpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        daylabel = new javax.swing.JLabel();
        monthlabel = new javax.swing.JLabel();
        yearlabel = new javax.swing.JLabel();
        dayspnr = new javax.swing.JSpinner();
        monthspnr = new javax.swing.JSpinner();
        yearspnr = new javax.swing.JSpinner();
        calculatebtn = new javax.swing.JButton();
        agelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Birthday");

        bgpanel.setBackground(new java.awt.Color(50, 62, 143));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 213, 22));
        jLabel1.setText("Birthdate/Age Computation");

        daylabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        daylabel.setForeground(new java.awt.Color(255, 213, 22));
        daylabel.setText("Day: ");

        monthlabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        monthlabel.setForeground(new java.awt.Color(255, 213, 22));
        monthlabel.setText("Month:");

        yearlabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        yearlabel.setForeground(new java.awt.Color(255, 213, 22));
        yearlabel.setText("Year:");

        dayspnr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        dayspnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dayspnrStateChanged(evt);
            }
        });

        monthspnr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        yearspnr.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2023, 1));

        calculatebtn.setText("Calculate");
        calculatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebtnActionPerformed(evt);
            }
        });

        agelabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        agelabel.setForeground(new java.awt.Color(255, 213, 22));
        agelabel.setText("Age:");

        datelabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 212, 22));
        datelabel.setText("Birthdate: ");

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel1)
                            .addGap(68, 68, 68))
                        .addGroup(bgpanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(calculatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bgpanelLayout.createSequentialGroup()
                                    .addComponent(daylabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dayspnr, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(monthlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(monthspnr, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(yearlabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yearspnr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelabel)
                            .addComponent(agelabel))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daylabel)
                    .addComponent(monthlabel)
                    .addComponent(yearlabel)
                    .addComponent(dayspnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthspnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearspnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(calculatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(agelabel)
                .addGap(18, 18, 18)
                .addComponent(datelabel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dayspnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dayspnrStateChanged
        int day = (int) dayspnr.getValue();
    }//GEN-LAST:event_dayspnrStateChanged

    private void calculatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebtnActionPerformed
        int day = (int) dayspnr.getValue();
        int month = (int) monthspnr.getValue();
        int year = (int) yearspnr.getValue();
        int currentYear = 2024;
        
        String birthday = monthname(month) + " " + day + " " + year;
        
        int age = currentYear - year;
        
        agelabel.setText("Age: " + age );
        datelabel.setText("Birthdate: " + birthday);
    }//GEN-LAST:event_calculatebtnActionPerformed
    private String monthname(int month){
        switch (month){
            case 1:
                return "January";
            case 2:
                return "Febuary";
            case 3:
                return"March";
            case 4: 
                return "April";
            case 5:
                return "May";
            case 6:
                return "June";
            case 7:
                return "July";
            case 8:
                return "August";
            case 9:
                return "September";
            case 10:
                return "October";
            case 11:
                return "November";
            case 12:
                return "December";
            default:
                return "";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Birthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Birthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Birthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Birthdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Birthdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelabel;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JButton calculatebtn;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel daylabel;
    private javax.swing.JSpinner dayspnr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel monthlabel;
    private javax.swing.JSpinner monthspnr;
    private javax.swing.JLabel yearlabel;
    private javax.swing.JSpinner yearspnr;
    // End of variables declaration//GEN-END:variables
}
